#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cargo
# autospec version: v12
# autospec commit: fbcebd0
#
Name     : cbindgen
Version  : 0.26.0
Release  : 1
URL      : https://github.com/mozilla/cbindgen/archive/refs/tags/0.26.0.tar.gz
Source0  : https://github.com/mozilla/cbindgen/archive/refs/tags/0.26.0.tar.gz
Source1  : http://localhost/vendor/cbindgen/snapshot/cbindgen-2024-06-07-08-33-30.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MPL-2.0
Requires: cbindgen-bin = %{version}-%{release}
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# `cbindgen` &emsp; [![Build Status]][actions] [![Latest Version]][crates.io] [![Api Rustdoc]][rustdoc] [![Rust](https://img.shields.io/badge/rust-1.64%2B-blue.svg?maxAge=3600)](https://github.com/mozilla/cbindgen)

%package bin
Summary: bin components for the cbindgen package.
Group: Binaries

%description bin
bin components for the cbindgen package.


%prep
%setup -q -n cbindgen-0.26.0
cd %{_builddir}
tar xf %{_sourcedir}/cbindgen-2024-06-07-08-33-30.tar.xz
cd %{_builddir}/cbindgen-0.26.0
mkdir -p ./vendor
cp -r %{_builddir}/cbindgen-2024-06-07-08-33-30/* %{_builddir}/cbindgen-0.26.0/./vendor
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cargo build --release --frozen --all-targets

%install
install -Dm0755 ./target/release/%{NAME} %{buildroot}%{_bindir}/%{NAME}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cbindgen
